apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          env:
            - name: GOOGLE_API_KEY
              value: {{ .Values.api_key }}
          ports:
            - containerPort: {{ .Values.port }}
              name: http-port
          startupProbe:
            httpGet:
              path: /v1/systems/ping
              port: http-port
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/systems/ping
              port: http-port
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /v1/systems/ping
              port: http-port
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
